management:
  security:
    enabled: false

server:
  port: &port 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/

spring:
  application:
    name: backend-service
